name: Build 
run-name: Building Test
on:
  push:
    branches:
      - dev
jobs:
  Build-Portfolio-Test:
    env:
      SERVER: preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '20.19.1'
      - run: npm install
      - run: npm run build
      - name: Auto merge
        if: ${{ success() }}
        uses: devmasx/merge-branch@master
        with:
          type: now
          head_to_merge: ${{ github.ref }}
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}


